(() => {
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
  const hud=document.getElementById('hud'),legend=document.getElementById('legend'),progressBar=document.getElementById('progressBar'),timerEl=document.getElementById('timer'),titleScreen=document.getElementById('titleScreen'),gameoverScreen=document.getElementById('gameoverScreen'),clearScreen=document.getElementById('clearScreen'),stageList=document.getElementById('stageList'),retryBtn=document.getElementById('retryBtn'),nextBtn=document.getElementById('nextBtn'),backBtnOver=document.getElementById('backBtnOver'),backBtnClear=document.getElementById('backBtnClear'),clearTimeEl=document.getElementById('clearTime'),needleName=document.getElementById('needleName');
  let W,H,cx,cy,R,safeBand,needleOffset,mode='title',stageIndex=0,startTime=null,elapsed=0,currentState=null,needle=null,handlePos=null,failPoint=null,clearLift=0,audioCtx=null,lastScratch=0,lastOutside=0;
  const N=420,targetR=new Float32Array(N);let shapePts=[],shapePath=null,traced=new Array(N).fill(false),tracedCount=0,particles=[];
  function heartRadius(t,Rb){const p=-t,s=Math.sin(p),c=Math.cos(p),r=2-2*s+s*Math.sqrt(Math.abs(c))/(s+1.4);return r/4*Rb*1.18}
  function starRadius(t,Rb){const step=Math.PI/5;let a=t+Math.PI/2;a=((a%(2*step))+2*step)%(2*step);if(a>step)a=2*step-a;const ro=Rb*1.12,ri=Rb*.46,xA=ro,xB=ri*Math.cos(step),yB=ri*Math.sin(step),C=-xA*yB,d=Math.sin(a)*(xB-xA)-Math.cos(a)*yB;return C/d}
  const STAGES=[{name:'日の丸',shape:(t,r)=>r,fill:'188,0,45'},{name:'ハート',shape:heartRadius,fill:'255,63,110'},{name:'星',shape:starRadius,fill:'255,196,42'}];
  function renderStages(){stageList.innerHTML='';STAGES.forEach((s,i)=>{const b=document.createElement('button');b.className='stageBtn';b.innerHTML=`<span class="num">${i+1}</span><span>${s.name}</span>`;b.onclick=()=>startGame(i);stageList.appendChild(b)})}
  function resize(){const size=Math.min(innerWidth,innerHeight)*.86;canvas.width=size*devicePixelRatio;canvas.height=size*devicePixelRatio;canvas.style.width=size+'px';canvas.style.height=size+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);W=size;H=size;cx=W/2;cy=H/2;R=W*.30;safeBand=W*.020;needleOffset=W*.16;buildStage();draw()}
  function buildStage(){shapePts=[];shapePath=new Path2D();for(let i=0;i<N;i++){const a=i/N*Math.PI*2,r=STAGES[stageIndex].shape(a,R);targetR[i]=r;const x=cx+r*Math.cos(a),y=cy+r*Math.sin(a);shapePts.push({x,y});i?shapePath.lineTo(x,y):shapePath.moveTo(x,y)}shapePath.closePath()}
  function show(el){[titleScreen,gameoverScreen,clearScreen].forEach(x=>x.classList.add('hidden'));if(el)el.classList.remove('hidden')}
  function reset(){traced.fill(false);tracedCount=0;currentState=null;needle=null;handlePos=null;startTime=null;elapsed=0;failPoint=null;clearLift=0;particles=[];progressBar.style.width='0%';timerEl.textContent='0.0s'}
  function startGame(i){stageIndex=i;buildStage();reset();mode='playing';needleName.textContent=STAGES[i].name;show(null);hud.classList.remove('hidden');legend.classList.remove('hidden')}
  function stageSelect(){mode='title';hud.classList.add('hidden');legend.classList.add('hidden');show(titleScreen)}
  function pointer(e){const r=canvas.getBoundingClientRect(),t=e.touches?e.touches[0]:e;return{x:t.clientX-r.left,y:t.clientY-r.top}}
  function bucket(a){return Math.round((((a*180/Math.PI)+360)%360)/360*N)%N}
  function vibrate(p){if(navigator.vibrate)try{navigator.vibrate(p)}catch(_){} }
  function audio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)()}
  function tone(f,d,v=.04,type='triangle'){try{audio();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(v,n+.005);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(audioCtx.destination);o.start(n);o.stop(n+d+.02)}catch(_){} }
  function scratch(){const n=performance.now();if(n-lastScratch<58)return;lastScratch=n;tone(900+Math.random()*420,.025,.025,'square');vibrate(3)}
  function outside(){const n=performance.now();if(n-lastOutside<220)return;lastOutside=n;tone(230,.05,.025);vibrate(5)}
  function dust(x,y){for(let i=0;i<(Math.random()>.45?2:1);i++)particles.push({x,y,vx:(Math.random()-.5)*1.6,vy:-.5-Math.random()*1.7,life:18+Math.random()*18,size:1+Math.random()*2.5})}
  function move(e){if(mode!=='playing')return;e.preventDefault();const p=pointer(e);handlePos=p;const off=Math.min(needleOffset,Math.max(0,p.y-W*.06));let tip={x:p.x,y:p.y-off};if(startTime===null)startTime=performance.now();let dx=tip.x-cx,dy=tip.y-cy,dist=Math.hypot(dx,dy),ang=Math.atan2(dy,dx),b=bucket(ang),diff=dist-targetR[b];const snap=safeBand*1.85;if(Math.abs(diff)<snap){const d={x:cx+targetR[b]*Math.cos(ang),y:cy+targetR[b]*Math.sin(ang)},s=.42;tip={x:tip.x+(d.x-tip.x)*s,y:tip.y+(d.y-tip.y)*s}}needle=tip;dx=tip.x-cx;dy=tip.y-cy;dist=Math.hypot(dx,dy);ang=Math.atan2(dy,dx);b=bucket(ang);diff=dist-targetR[b];const state=Math.abs(diff)<=safeBand?'green':diff>safeBand?'white':'red';if(state!==currentState){currentState=state;if(state==='green')vibrate(10);else if(state==='white')outside();else vibrate([50,20,80])}if(state==='green'){for(let i=-2;i<=2;i++){const k=(b+i+N)%N;if(!traced[k]){traced[k]=true;tracedCount++}}dust(tip.x,tip.y);scratch();progressBar.style.width=(tracedCount/N*100).toFixed(1)+'%';if(tracedCount>=N)clearGame()}else if(state==='red')gameOver(tip.x,tip.y)}
  function end(){if(mode!=='playing')return;needle=null;handlePos=null;currentState=null}
  function gameOver(x,y){mode='gameover';failPoint={x,y};tone(120,.18,.08,'sawtooth');setTimeout(()=>tone(80,.2,.06,'square'),45);vibrate([60,30,90]);setTimeout(()=>{hud.classList.add('hidden');legend.classList.add('hidden');show(gameoverScreen)},480)}
  function clearGame(){mode='clearing';needle=null;handlePos=null;tone(260,.05,.03);setTimeout(()=>tone(520,.08,.06),120);setTimeout(()=>tone(780,.12,.07),220);vibrate([25,30,25,30,60]);setTimeout(()=>{mode='clear';hud.classList.add('hidden');legend.classList.add('hidden');clearTimeEl.textContent=elapsed.toFixed(2)+'s';nextBtn.textContent=stageIndex===STAGES.length-1?'さいしょのステージへ':'つぎのステージへ';show(clearScreen)},650)}
  function updateParticles(){particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.05;p.life--})}
  function draw(){ctx.clearRect(0,0,W,H);const plateR=R+safeBand+W*.09,g=ctx.createRadialGradient(cx,cy-plateR*.2,plateR*.1,cx,cy,plateR);g.addColorStop(0,'#fffaf0');g.addColorStop(1,'#e7d9ad');ctx.beginPath();ctx.arc(cx,cy,plateR,0,Math.PI*2);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(120,90,40,.25)';ctx.lineWidth=2;ctx.stroke();if(shapePath){ctx.save();if(mode==='clearing')clearLift=Math.min(1,clearLift+.055);const lift=mode==='clearing'?clearLift*W*.10:0,scale=mode==='clearing'?1+clearLift*.035:1;ctx.translate(cx,cy-lift);ctx.scale(scale,scale);ctx.translate(-cx,-cy);ctx.fillStyle=`rgba(${STAGES[stageIndex].fill},${.10+.55*(tracedCount/N)})`;ctx.shadowColor=mode==='clearing'?'rgba(0,0,0,.35)':'transparent';ctx.shadowBlur=mode==='clearing'?18:0;ctx.shadowOffsetY=mode==='clearing'?12:0;ctx.fill(shapePath);for(let i=0;i<N;i++){const a=shapePts[i],b=shapePts[(i+1)%N];ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);if(traced[i]){ctx.strokeStyle='rgba(255,250,226,.98)';ctx.lineWidth=7;ctx.stroke();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle='rgba(63,224,138,.64)';ctx.lineWidth=3;ctx.stroke()}else{ctx.strokeStyle='rgba(104,60,24,.46)';ctx.lineWidth=3;ctx.setLineDash([2,5]);ctx.stroke();ctx.setLineDash([])}}ctx.restore()}if(needle&&handlePos){let col=currentState==='green'?'#3fe08a':currentState==='red'?'#ff3b3b':'#fff6d8';const shaft=ctx.createLinearGradient(handlePos.x,handlePos.y,needle.x,needle.y);shaft.addColorStop(0,'#8b5a2b');shaft.addColorStop(.55,'#d3a66a');shaft.addColorStop(1,'#d9dee3');ctx.beginPath();ctx.moveTo(handlePos.x,handlePos.y);ctx.lineTo(needle.x,needle.y);ctx.lineWidth=W*.013;ctx.lineCap='round';ctx.strokeStyle=shaft;ctx.stroke();ctx.beginPath();ctx.arc(handlePos.x,handlePos.y,W*.026,0,Math.PI*2);ctx.fillStyle='rgba(190,135,74,.55)';ctx.fill();ctx.beginPath();ctx.arc(needle.x,needle.y,W*.014,0,Math.PI*2);ctx.fillStyle=col;ctx.shadowColor=col;ctx.shadowBlur=16;ctx.fill();ctx.shadowBlur=0}particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/30);ctx.fillStyle='#fff7da';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;if(mode==='gameover'&&failPoint){ctx.strokeStyle='rgba(255,59,59,.9)';ctx.lineWidth=2;for(let i=0;i<7;i++){const a=i/7*Math.PI*2+.35,l=W*(.05+(i%3)*.025);ctx.beginPath();ctx.moveTo(failPoint.x,failPoint.y);ctx.lineTo(failPoint.x+Math.cos(a)*l,failPoint.y+Math.sin(a)*l);ctx.stroke()}}}
  function loop(){if(mode==='playing'&&startTime!==null){elapsed=(performance.now()-startTime)/1000;timerEl.textContent=elapsed.toFixed(1)+'s'}updateParticles();draw();requestAnimationFrame(loop)}
  canvas.addEventListener('touchstart',move,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end,{passive:false});canvas.addEventListener('mousedown',move);canvas.addEventListener('mousemove',e=>{if(e.buttons===1)move(e)});canvas.addEventListener('mouseup',end);retryBtn.onclick=()=>startGame(stageIndex);nextBtn.onclick=()=>startGame((stageIndex+1)%STAGES.length);backBtnOver.onclick=stageSelect;backBtnClear.onclick=stageSelect;renderStages();addEventListener('resize',resize);resize();loop();
})();
